# Generated by Django 4.0.4 on 2022-11-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='عنوان')),
                ('price', models.IntegerField(verbose_name='قیمت')),
            ],
        ),
    ]
