# Generated by Django 4.0.4 on 2022-11-16 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='payment',
            new_name='order',
        ),
    ]
